apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-dep
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
