apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: board-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: board-dep
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
