apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-dep
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
