apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-dep
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

