---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gold
  labels:
    app: gold
spec:
  storageClassName: "gold"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
