---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silver
  labels:
    app: silver
spec:
  storageClassName: "silver"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
