apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: file-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-dep
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

