---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx
spec:
  storageClassName: "nginx-sc"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
