apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: test/nginx
    name: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: nginx-vol
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-pvc

