apiVersion: v1
kind: Service
metadata:
  annotations:
  name: monitoring
  namespace: admin
spec:
  type: ExternalName
  externalName: monitoring-grafana.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: argocd
  namespace: admin
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
