apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: admin
spec:
  type: ExternalName
  externalName: prometheus-grafana.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: admin
spec:
  type: ExternalName
  externalName: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: admin
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
