apiVersion: v1
kind: Service
metadata:
  annotations:
  name: prometheus-grafana
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: prometheus-kube-prometheus-prometheus
spec:
  type: ExternalName
  externalName: prometheus.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: argocdserver
spec:
  type: ExternalName
  externalName: argocd.argocd.svc.cluster.local

