---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bronze
  labels:
    app: bronze
spec:
  storageClassName: "bronze"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
